# Generated by Django 4.1.5 on 2023-01-27 15:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0002_perro"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Perro",
            new_name="Fish",
        ),
    ]
